import { ApplicationConfig } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideToastr } from 'ngx-toastr';
import { routes } from './app.routes';
import { jwtInterceptor } from './core/interceptors/jwt.interceptor';
import { errorInterceptor } from './core/interceptors/error.interceptor';
import { provideIcons } from '@ng-icons/core';
import {
  heroChartBar,
  heroCalendar,
  heroUsers,
  heroUserGroup,
  heroCalendarDays,
  heroClipboardDocument,
  heroClipboardDocumentList,
  heroFolderOpen,
  heroClock,
  heroBriefcase,
  heroIdentification,
  heroBanknotes,
  heroReceiptPercent,
  heroChartPie,
  heroCog6Tooth,
  heroUserCircle,
  heroCheck,
  heroXMark,
  heroDocumentText,
  heroBell,
  heroCreditCard,
  heroUserPlus,
  heroDocumentCheck,
  heroArrowRightOnRectangle,
  heroMagnifyingGlass,
  heroMoon,
  heroChevronDown,
  heroChevronUp,
  heroQuestionMarkCircle,
  heroUser,
  heroArrowRight,
  heroLockClosed,
  heroLanguage,
  heroTrash,
  heroArrowTrendingUp,
  heroArrowTrendingDown,
  heroComputerDesktop,
  heroExclamationTriangle,
  heroEye,
  heroPencil,
  heroArrowDownTray,
  heroEllipsisVertical,
  heroArrowLeft,
  heroShieldCheck,
  heroQrCode,
  heroFunnel,
  heroPlusCircle,
  heroPlus,
  heroPencilSquare,
  heroCheckCircle,
  heroXCircle,
  heroBuildingOffice,
  heroPrinter,
  heroBellAlert,
  heroArrowPath,
  heroPhone,
  heroEnvelope,
  heroMapPin,
  heroHashtag,
  heroHeart,
  heroBeaker,
  heroInformationCircle,
  heroBolt,
  heroArrowUpTray,
  heroChevronLeft,
  heroChevronRight,
  heroCheckBadge,
  heroExclamationCircle,
  heroScale,
  heroArrowsUpDown,
  heroCalculator,
  heroFire,
  heroPhoto,
  heroDocumentDuplicate
} from '@ng-icons/heroicons/outline';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(withInterceptors([jwtInterceptor, errorInterceptor])),
    provideAnimations(),
    provideToastr({ positionClass: 'toast-top-right', timeOut: 3000 }),
    provideIcons({
      heroChartBar,
      heroCalendar,
      heroUsers,
      heroUserGroup,
      heroCalendarDays,
      heroClipboardDocument,
      heroClipboardDocumentList,
      heroFolderOpen,
      heroClock,
      heroBriefcase,
      heroIdentification,
      heroBanknotes,
      heroReceiptPercent,
      heroChartPie,
      heroCog6Tooth,
      heroUserCircle,
      heroCheck,
      heroXMark,
      heroDocumentText,
      heroBell,
      heroCreditCard,
      heroUserPlus,
      heroDocumentCheck,
      heroArrowRightOnRectangle,
      heroMagnifyingGlass,
      heroMoon,
      heroChevronDown,
      heroChevronUp,
      heroQuestionMarkCircle,
      heroUser,
      heroArrowRight,
      heroLockClosed,
      heroLanguage,
      heroTrash,
      heroArrowTrendingUp,
      heroArrowTrendingDown,
      heroComputerDesktop,
      heroExclamationTriangle,
      heroEye,
      heroPencil,
      heroArrowDownTray,
      heroEllipsisVertical,
      heroArrowLeft,
      heroShieldCheck,
      heroQrCode,
      heroFunnel,
      heroPlusCircle,
      heroPlus,
      heroPencilSquare,
      heroCheckBadge,
      heroCheckCircle,
      heroXCircle,
      heroBuildingOffice,
      heroPrinter,
      heroBellAlert,
      heroArrowPath,
      heroPhone,
      heroEnvelope,
      heroMapPin,
      heroHashtag,
      heroHeart,
      heroBeaker,
      heroInformationCircle,
      heroBolt,
      heroArrowUpTray,
      heroChevronLeft,
      heroChevronRight,
      heroExclamationCircle,
      heroScale,
      heroArrowsUpDown,
      heroCalculator,
      heroFire,
      heroPhoto,
      heroDocumentDuplicate
    })
  ]
};

